version: '3'

services:
  db:
    image: mysql:5.7.34
    command: --init-file /var/lib/docker/volumes/db/init.sql --innodb-use-native-aio=0 --explicit_defaults_for_timestamp=false
    volumes:
      - ./db:/var/lib/docker/volumes/db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db

  server:
    image: server
    volumes:
     - .:/go/src/mvc_golang
    ports:
      - 8090:8090
    depends_on:
      - db
   